baseURL = "https://shuxhan.com/"
languageCode = "zh-cn"
title = "æ±‚ç´¢æ—¥è®°"
theme = "nov"
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""     
    lineNoStart = 1  
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
    anchorlinenos = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[author]
  name = "Nov8nana"
  homepage = "https://shuxhan.com"

[params]
  mainSections = ["posts"]
  iconTitle = "ğŸ˜  Nov8nana"
  Description = "è·¯æ¼«æ¼«å…¶ä¿®è¿œå…®ï¼Œå¾å°†ä¸Šä¸‹è€Œæ±‚ç´¢ï¼"
  CusdisId = "c1d43485-e8a7-4895-972e-247eddaf242d" # Cusdis idå¡«å†™
  extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
  favicon = "https://img.shuxhan.com/favicon.png"
  GithubId = "Nov8nana"

[[params.socials]]
  name = "About"
  link = "/about"

[[params.socials]]
  name = "Repos"
  link = "/repos"

[[params.socials]]
  name = "Github"
  link = "https://github.com/Nov8nana"

