# baseURL = "https://shuxhan.com/"
# languageCode = "zh-cn"
# title = "æ±‚ç´¢æ—¥è®°"
# theme = "nov"
# paginate = 10

# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true
#   [markup.highlight]
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""     
#     lineNoStart = 1  
#     lineNos = false
#     lineNumbersInTable = false
#     noClasses = true
#     style = "dracula"
#     tabWidth = 4
#     anchorlinenos = false
#   [markup.tableOfContents]
#     endLevel = 3
#     ordered = false
#     startLevel = 2

# [author]
#   name = "Nov8nana"
#   homepage = "https://shuxhan.com"

# [params]
#   mainSections = ["posts"]
#   iconTitle = "ğŸ˜  Nov8nana' blog"
#   Description = "è·¯æ¼«æ¼«å…¶ä¿®è¿œå…®ï¼Œå¾å°†ä¸Šä¸‹è€Œæ±‚ç´¢ï¼"
#   CusdisId = "c1d43485-e8a7-4895-972e-247eddaf242d" # Cusdis idå¡«å†™
#   extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
#   favicon = "https://img.shuxhan.com/favicon.png"
#   GithubId = "Nov8nana"

# [[params.socials]]
#   name = "About"
#   link = "/about"
# [[params.socials]]
#   name = "Repos"
#   link = "/repos"
# [[params.socials]]
#   name = "Github"
#   link = "https://github.com/Nov8nana"


# baseurl = "https://shuxhan.com"
# title = "æ±‚ç´¢æ—¥è®°"
# author = "Nov8nana"
# copyright = "Copyright Â© 2008â€“2018, @JeffProd"
# canonifyurls = true
# paginate = 10
# summaryLength = 3
# theme = "huibo"

# [taxonomies]
#     tag = "tags"
#     archive = "archives"

# [params]
#   icon = "https://img.shuxhan.com/favicon.png"
#   mainSections = ["posts"]
#   logo = "Nov8nana' blog"


# [[params.socials]]
#   name = "About"
#   link = "/about"

# [[params.socials]]
#   name = "Github"
#   link = "https://github.com/Nov8nana"


baseURL = "https://shuxhan.com/"
languageCode = "en-us"
title = "æ±‚ç´¢æ—¥è®°"
theme = "huibo"
paginate = 7

copyright = "Â© Copyright notice"

[permalinks]
  # posts = "/:year/:month/:title"

[params]
  favicon = "https://img.shuxhan.com/favicon.png"
	subtitle = "è·¯æ¼«æ¼«å…¶ä¿®è¿œå…®ï¼Œå¾å°†ä¸Šä¸‹è€Œæ±‚ç´¢ï¼"
 CusdisId = "c1d43485-e8a7-4895-972e-247eddaf242d" # Cusdis idå¡«å†™
	featherIconsCDN = false

	# Enable a table of contents
	toc = true
  maxTags = 7
  wpm = 250



[[menu.main]]
name = "é¦–é¡µ"
url = "/"
weight = 1

[[menu.main]]
name = "å½’æ¡£"
url = "/posts"
weight = 2

[[menu.main]]
name = "å…³äºæˆ‘"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Nov8nana/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""     
    lineNoStart = 1  
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
    anchorlinenos = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2